grid-columns: 2
style.fill: transparent

presentation: {
  label: Presenter WebApp
  style.fill: transparent
  style.stroke: blue
}

svg: {
  label: SVG
  style.fill: transparent
  style.stroke: orange
  link: https://google.com
}

presentation -> svg: {
  style.stroke: blue
  style.animated: true
}
